### ISSUE TITLE
Update main Jobs page and add new work group buttons

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-data-tracker#101]
**User Story**
> As a Markings technician, I can see a list of only the jobs that are in my work group and grouped by requester so that I can prioritize my work. 

**FUNCTION**
 - Add new menu 
 - Add pages for each work group with
     - Filter by status
     - Group by requester

**Comment by dianamartin** [comment]
REFERENCE: 
[Main Jobs table](https://atd.knack.com/21-may-2019-test-signs-migration-atd-data-tracker#home/work-orders-markings/markings/work-jobs-markings/)
[Long line Jobs table](https://atd.knack.com/21-may-2019-test-signs-migration-atd-data-tracker#home/work-orders-markings/markings/work-jobs-markings/long-line/)

**Comment by dianamartin** [comment]
Rename button to "Main Jobs page" from "All Jobs"

**Comment by amenity** [comment]
@dianamartin already put some work in on this, but not necessary for Signs Migration, actually an enhancement down the line.
