### ISSUE TITLE
Update Markings CSR workflow diagram 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-data-tracker#102]
Based on notes from 5/23 meeting: [Annotated 311 CSR Workflow PDF](https://github.com/cityofaustin/atd-knack-data-tracker/files/3214843/CSR_311_Markings_Workflow_Future_20171019_Updated_Comments.pdf)

(First send to Christina and Kati for review.)

**Comment by dianamartin** [comment]
Will wait for Kati and Christina's feedback

**Comment by amenity** [comment]
Waiting for feedback from Christina and Kati.

**Comment by dianamartin** [comment]
Emailed Kati and Christina on 6/7
>I’ve updated the workflows. The markings one show the current state and the signs one is supposed to depict the future state. Please review and let me know if anything is inaccurate.
