### ISSUE TITLE
Meeting: Traffic Volume mapping kick off at Barton Oaks

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#112]
Joel sent out meeting invite to Jaime. Jaime forwarded it to Mateo and I so we can all attend and make sure that everyone is in agreement of what the project direction is. 

6/4 @ Barton Oaks - Colorado Rm

@johnclary: did you want to call in? Currently no phone line, but we can forward you the invite and you can ask Joel to set it up or we can just call you, either way.

**Comment by johnclary** [comment]
Great—yes i’d like to call in. You can pull conference line from our monday meeting.

On May 31, 2019, at 08:40, Diana Martin <notifications@github.com<mailto:notifications@github.com>> wrote:


Joel sent out meeting invite to Jaime. Jaime forwarded it to Mateo and I so we can all attend and make sure that everyone is in agreement of what the project direction is.

@johnclary<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohnclary&data=02%7C01%7CJohn.Clary%40austintexas.gov%7Cca5e346fda75489eb86408d6e5de5ce2%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C636949140538823623&sdata=LV5fgLnzTjW7rSd2t56GZ1n94IcYh4zKZq8qPLAU1KM%3D&reserved=0>: did you want to call in? Currently no phone line, but we can forward you the invite and you can ask Joel to set it up or we can just call you, either way.

**Comment by jaime-mckeown** [comment]
Attended meeting with Diana yesterday. Discussed the 3 versions of data that were created to help Frank with project. More details about data in GIS Issue:
https://github.com/cityofaustin/atd-knack-data-tracker/issues/115
