### ISSUE TITLE
Signs Migration Knack work session - spatial

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-data-tracker#119]
After feature prioritization, Diana and John should meet and go over the Must Have features related to location and determine how they will be implemented and size them accordingly. 

Need to discuss the proposed workflows.

**Comment by dianamartin** [comment]
My Notes:
>We were going to review on Monday, June 17th to determine which spatial approach we should take. Use the Custom JS in Knack and or Fulrum integration with Knack. Depending on what Mateo/Mike and Sergio come up with as far as level of effort and tangible deliverables will be what we evaluate at our meeting.
