### ISSUE TITLE
Add field "HARDWARE_ID" to detector object table

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#120]
Requester: **Kenneth "Ken" Perrine**
Division: **CTR**

URL: _http://transportation.austintexas.io/data-tracker/#home/detection-reports/detectors-gridsmart/_

Insert Quote/Email 
>John, please find attached a CSV file that has ATD device IDs matched up with GRIDSMART hardware IDs, resolved via IP address. I could, of course, get these only for devices that were responsive. Some IDs are duplicated, because upon quick inspection it appears that the respective Knack entries are duplicated. 

File we received is actually a .txt file.

**Comment by dianamartin** [comment]
Please do the following:
1. Convert .txt file `GS_ATD_IDs_20190531.txt` into .csv table
located here: **`G:\ATD\ATD_GIS\02_ENT_APPLICATIONS\AMD_DATA_TRACKER\Signals`**
2. Add field "HARDWARE_ID" on `signal_detectors` [object table] (https://builder.knack.com/atd/amd#data/object_98/fields)

**Comment by johnclary** [comment]
@dianamartin @wchIV you can import them as-is. Thanks.

**Comment by dianamartin** [comment]
@wchIV You can import these to the Production environment, I just reviewed them in Test and the 50 records look fine to me.

**Comment by wchIV** [comment]
Went ahead and imported the CSV on the production environment to HARDWARE_ID in the signal_detectors table.  It appears to have worked without any issues.

**Comment by dianamartin** [comment]
@wchIV On this page: https://builder.knack.com/atd/amd#pages/scene_1005
Can you please add the `HARDWARE_ID` field you added and rename with proper case, take out the under bar. I would put it maybe after Detector ID.

![image](https://user-images.githubusercontent.com/21112975/61641561-f9d98500-ac64-11e9-911e-a2ee08137e28.png)

**Comment by wchIV** [comment]
Put the new Hardware ID field in the Gridsmart Detectors page after Detector ID on the production data tracker.  Feature is complete now.
