### ISSUE TITLE
Data Tracker Theme updated to new theme

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#127]
John 
DTS

Need to review Billy H. comments on when we switched Data Tracker in Test to new theme. What pages broke and document them so that when we make the switch in PROD.

Folder Location: **_G:\ATD\ATD_GIS\02_ENT_APPLICATIONS\AMD_DATA_TRACKER_**

Might need to get Mateo's help on doing redirects from the austintexas.io site to he new Knack database.

**Comment by amenity** [comment]
Not urgent since we have a standalone app.
