### ISSUE TITLE
Duplicate Traffic Signal 311 SR created via API

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-data-tracker#131]
Two identical records were created in `tmc_issues` via the 311 integration with SR # 19-00215534.

1. TMC19-126955 < (status: new)
2. TMC 19-126950 < (status in progress; has work order attached

Validation rules are in place to prevent this, but apparently failed.

**Comment by johnclary** [comment]
I closed TMC19-126955 using the "closed: duplicate" activity. This updated the status of the duplicate TMC issue to Closed (duplicate), and I deleted the activity itself so as to prevent it from being sent back to 311. Reviewed issue in 311 CSR and confirmed that it has the correct status: in progress.

**Comment by johnclary** [comment]
@dianamartin i fixed everything in the data tracker. when you have time, would you open an issue with Knack and ask them how this passed validation? We have a rule in place to prevent records from being created with the same SR number.

**Comment by johnclary** [comment]
@dianamartin 

Knack Record ID: 5cfe9de87873f5000a454589
TMC_ISSUE_ID: TMC19-126955
CSR_ID: 19-00215534

Knack Record ID: 5cfe9de71dab26000aa51316
TMC_ISSUE_ID: 19-0126950
CSR_ID: 19-00215534

**Comment by dianamartin** [comment]
@johnclary Knack support ticket was turned in.

**Comment by dianamartin** [comment]
Response from Knack
>Thank you for reaching out to us. I've taken a look here, and it seems that both of these records were added via API at the same time. Currently, there is a known issue related to asynchronous API requests bypassing unique field requirements, which I believe is likely the cause here. 

>When hitting the Knack API asynchronously, requests can come in quick enough that the second request checks for uniqueness before the first request has finished committing, and the unique field requirements are missed. 

>A possible solution here might be to use promises in JavaScript, or some other serialization package-tool, so that the second request doesn't start until the first one finishes. I would recommend testing this in a non-production app first to ensure expected behavior.

>Let me know if you have any questions, or if this doesn't seem to explain the behavior you're seeing here.
