### ISSUE TITLE
Define Call Back SR Process

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#137]
1. Nothing - SR stays in main table until the next day, sign specialist converts to WO the next day for tech to fill out. 
2. New Emergency Call back page and button - Filtered emergency SRs show on this page, create "new user role" - (Call back user) 
- Allow Tech to assign SR to themselves
- WO gets created

Decision: 
- create user role (on-call people can see this page)
- create user role (only assigned person - changes weekly)
- add button for all techs to see (people don't click it if they don't have to)

**Comment by dianamartin** [comment]
Want to add button

"My Work Orders" page
add a button for "Call Back SRs"
create a new page for "Emergency SRs" only

**Comment by dianamartin** [comment]
Christina will reach out to Kenny to determine what they'd like the process to be like

**Comment by amenity** [comment]
They take the phone call, say they're going, then add all the information the next day.
