### ISSUE TITLE
Created `work_orders_signs` object table

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#138]
John and I decided to split signs and markings from one object table to their own 

Recreate all connections
Create all connections – to new `work_order _signs`
- [x] - Accounts 
- [x] - Signs fleet  
- [x] - Signs materials 
- [x] - Comments 
- [x] - Attachments 
- [x] - Signs spatial (new!) 
- [x] - Signs Asset Spec (new!) - have to import this

**Comment by dianamartin** [comment]
exported `work_orders_signs_markings.csv`
saved as .xslx, removed markings records
imported `work_orders_signs_20190612.csv`
Kept only 5/1/2019

**Comment by dianamartin** [comment]
- [ ] Need to delete test records before we deploy everything

**Comment by dianamartin** [comment]
Emailed Christina 
>Was wondering when you’d be able to get me those spreadsheets? I have today, tomorrow and Monday afternoon to import them in and do some testing. I’m hoping to do it by the end of the week

**Comment by johnclary** [comment]
this is all done right? closing.

**Comment by dianamartin** [comment]
we just need to delete the test records from the table.
