### ISSUE TITLE
Fulcrum / Knack Integration Discovery

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-data-tracker#140]

**Comment by johnclary** [comment]
We’re considering doing an integration between Fulcrum and Knack. The integration will need to sync data in both directions between the two apps, and the data will be stored across multiple tables in each application.

Before Monday’s 2pm meeting, could you spend some time looking at the Fulcrum and Knack API docs and think about this best way to do this, and estimate level of effort?

We do already have a basic integration from Fulcrum to Knack in place. Our intern created it, and I suspect you’d want to re-factor or start from scratch. That repo is here: https://github.com/cityofaustin/atd-knack-fulcrum

**Comment by sergiogcx** [comment]
After speaking with @dianamartin, these are the tables in Knack that need to be imported into Fulcrum:

```
work_orders_signs_markings (which will later become work_order_signs)
work_order_signs_spatial
work_order_signs_assets (does not yet exist)
work_order_signs_images
work_orders_signs_markings_time_log

Plus, any supporting tables:
- Accounts
- fleet_vehicles
- etc.
```

**Comment by sergiogcx** [comment]
So far I have had luck exporting data out of Knack (all tables), I am working on Fulcrum trying to understand it and see if we can:

- Mass-upsert data
- Create tables through API

**Comment by sergiogcx** [comment]
This is the report on the discovery process:

https://docs.google.com/presentation/d/15h9NxTDyy22livoE9tg4CgnISa90ZvUxsFFjtbVOfSA/edit?usp=sharing
