### ISSUE TITLE
Signs Work Order Details Page for Geospatial UI

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-data-tracker#148]
@mateoclarke @mddilley there's some configuring left to be done before the work order details page is ready for the geospatial UI. Once complete I'll update this comment with all the details you need and confirm when ready.

Work in progress...

This is the primary scene (aka, page) where the geospatial UI needs to be embedded/linked to:
https://builder.knack.com/atd/amd#pages/scene_1028

**Comment by mateoclarke** [comment]
@johnclary Just to clarify... [this](https://builder.knack.com/atd/amd#pages/scene_1028) will be the production location right? Can we continue to use https://builder.knack.com/atd/21-may-2019-test-signs-migration-atd-data-tracker#pages/scene_716 as the development/testing location?

**Comment by mateoclarke** [comment]
@johnclary IRL today, you mentioned that this production page is ready. correct?

**Comment by johnclary** [comment]
@mateoclarke correct. go to town

**Comment by mateoclarke** [comment]
closing this out @johnclary, reopen if thats premature...
