### ISSUE TITLE
Enhancement/Feature Request: Add firmware field to Signal Priority page export

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-knack-data-tracker#150]
**Project Name**: 

Joshil wants the ability to export the firmware field that is currently visible on the normal [signals page](http://transportation.austintexas.io/data-tracker/#home/signals/signal-details/58164b9af9195edb2a5e3a07/) to also be exported via the [signal priority page](http://transportation.austintexas.io/data-tracker/#home/signal-priority/).

**Requested By**: 
Joshil

**Customer Priority**: 
- [x] Low
- [ ] Normal
- [ ] Urgent

**How would you rate the impact of this issue?**
- [ ] 0 - No Data Available 
- [ ] 1 - Severe Impact to Services
- [ ] 2 - Major Impact to Services
- [ ] 3 - Minor Loss of Services
- [x] 4 - Does Not Affect Services

**Is your feature request related to a problem? Please describe.**
His current process requires multiple exports and data merging just for one field.

**Describe the solution you'd like**
Add firmware column to Signal Priority page so that it is included in exports.

**Describe alternatives you've considered**
n/a

**Additional context**
![Screen Shot 2019-06-25 at 12 31 04 PM](https://user-images.githubusercontent.com/5697474/60119897-32a93b80-9745-11e9-93ea-e668cacc5061.png)

**Needed By Date**
n/a

**Comment by dianamartin** [comment]
Joshil came by and we discussed what he needed. The `signal_priority` table is a different table than the `signals` table, but already had a connection. 

- Created a `Firmware` field (text formula), referenced the `signal>FIRMWARE_STATUS` 
- Added new field to `signal_priority` table on **Signal Priority table** page
