### ISSUE TITLE
Add Single Sign On to new Signs & Markings app

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#154]
[Signs & Markings Operations app](https://atd.knack.com/signs-markings#home/)

**Comment by dianamartin** [comment]
@johnclary Is there any way to change the button on the home page from `coacd` to all caps, `COACD`?

**Comment by johnclary** [comment]
Yes, done. Even better, we turn this into a big button like with finance & purchasing. Will add a new issue.
