### ISSUE TITLE
TCP enhancements - New field "Billable" and add Status selctions

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#164]
Ryan Mooney/Ryan Ward
ROW

Asking for enhancement update to TCP Tracker

>Per Ryan Ward, **Wednesday, July 3, 2019 10:57 AM**, Could you get this update on the radar and would this be an ask that can be done by Tracy quickly? Below is the need:
•	New Attribute – Billable (Selection of `Yes` or `No`)
•	Status – Add `Pending Payment`; `Review Complete`; and `Approved` if it’s not already an option

>I believe that ROW is asking for new field to be added to the `tcp_submisson` table
-[ ] `Approved` status already exists
-[ ] `Review Complete`
-[ ] `Pending Payment`

**Comment by johnclary** [comment]
Question sent to Ryan M:
> These are the statuses we currently have:
>
> APPROVED
> REVIEW IN PROGRESS
> REJECTED
> RETURNED
> PENDING
> NO REVIEW REQUIRED
> 
You want to add "PENDING PAYMENT" in addition to the existing "PENDING"? If so, what is PENDING meant to > indicate?
> 
> 
> And, to confirm, we will add a "REVIEW COMPLETE" status, which is distinct from APPROVED?

**Comment by dianamartin** [comment]
@johnclary We should be asking Jonathan Thompson (ROW)

Per Mani's email
>Jonathan Thompson often has lots of inputs, so I would like to nominate him even though he is a contract employee.

**Comment by johnclary** [comment]
Waiting for further instruction from Mani. Moving to backlog.
