### ISSUE TITLE
Update Detection Reports - filter and add filters

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#165]
Brian Van De Walle
AMD

He emailed saying 
>**Signal Detection Status** report widget
Make sure that "DETECTION UNINSTALLED" is not included in this report

>**Detection Issues and Repairs** report widget
Add a filter that would let you specify a date range to this widget (i.e. DETECTION_STATUS_DATE)

**Comment by amenity** [comment]
@dianamartin is going to follow up with Van de Walle and confirm this is complete.

**Comment by dianamartin** [comment]
Talked to Brian VDW and he said he's using a different report widget to get his numbers. So the report widget in question is also fine now that we took the preset filter on it.
