### ISSUE TITLE
Migrate Signals form changes from TEST to PROD

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#187]
- [x] Created `new work order | mobile' form` page
- [x] Documented all form fields, form rules, display rules, record rules on [atd-data-tracker-wiki page](https://github.com/cityofaustin/atd-knack-data-tracker/wiki/Signals-Work-Order-%7C-FORMS)
- [x] Set page login to - `System Administrator`
- [x] Created new button on menu bar of My Work Orders page
- [x] Tested user roles to see if `Test-Tech` is able to see menu button
>can't see it
- [x] Tested user roles to see if `Systems Admin` is able to see menu button
>Yes, can see it

**Comment by dianamartin** [comment]
@mateoclarke @johnclary I think I'm done migrating the signals form from Test to Production. 

@mateoclarke You can start testing your signals mobile work order form from Production. Let me know if there are any snags.

**Comment by dianamartin** [comment]
@mateoclarke @johnclary I just realized i have to update the one on the main signals work order page. The "My Work Orders" page is updated though.

**Comment by mateoclarke** [comment]
@dianamartin - what's the status on this? Somehow we missed it during planning.

**Comment by dianamartin** [comment]
@mateoclarke Was working on it this morning, almost finalized. I need to talk to John to make sure of a workflow process. Should be done by COB if I can talk to John.

**Comment by dianamartin** [comment]
### My Work Orders | Signals
- [ ] New Work Order | FORM
>Both technician & supervisor use the same new work order form
- [ ] Edit Work Order | FORM

### Work Orders | Signals
- [ ] New Work Order | FORM
- [ ] Edit Work Order | FORM
>This had login restrictions for a technician. The edit forms are two separated forms. 

### Follow-up 
Do we still need the 2 separate edit forms. Use case for supervisor to not have techs edit the same form.

**Comment by dianamartin** [comment]
@mateoclarke App name is: `13 AUG 2019 | TEST - Austin Transportation Data Tracker`. I removed the rules for the System Administrator only. The technician can access those pages.
