### ISSUE TITLE
Compare signals work order status v. work order status new

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#190]
- [x] export `work_order_signals`
- [x] match the status new and status old to see if consistent

**Comment by dianamartin** [comment]
Of the 11,860 records, 22 records don't match.

**Comment by dianamartin** [comment]
@johnclary What should we do now?

**Comment by johnclary** [comment]
resolved. and matching all but for one, which appears to be an edge case of simultaneous editing: 
WRK19-061090. 

the only change i made was flipping `IN_PROGRESS` to `1` when a user saved a work order without submitting.
https://builder.knack.com/atd/amd#pages/scene_297/views/view_1197
