### ISSUE TITLE
Traffic Count Reporting Widgets

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-data-tracker#202]
From Jen:

Can you help us aggregate monthly statistics for the traffic count group? It may be helpful to break this down by request type, and also by geographic area (north/central/south).

We’re trying to get a more quantitative sense of the workload of this group and how it is changing over time.

Show trends over time

- Number of Requests each month
- Number Completed each month
- Time to completion (_Completed Date-Created Date_)

**Comment by dianamartin** [comment]
Surbhi asked for peer review
[Traffic Count Reporting page](https://atd.knack.com/13-aug-2019--test-austin-transportation-data-tracker#home/traffic-count-traffic-data-requests/reporting/)
>Wanted to get your feedback. From the requirements, this is what I gathered - Jen wanted to see a breakdown by request type (work type) and  geographic area for - Number of Requests each month

- Number Completed each month
- Time to completion (Completed Date-Created Date)

**Comment by SurbhiBakshi** [comment]
- Created first draft and sent a link to Jen and team to look at.
- Set up meeting with Jen and team for user review and feedback.
