### ISSUE TITLE
Customer Request: TCP Tracker Review Queue Reporting

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-knack-data-tracker#213]
**Submitted via email on 9/9/19 by Mani Kumar:**

Hello Tracy, I just went over the TCP Queue numbers with our staff (Laura Roy and Jonathan Thompson) and seems like there are some issues in fetching this information from the TCP Tracker/ database. In the TCP Tracker, there is a column for “Due Date”, but there isn’t one for the submittal date. Also, the not all the dates in the tracker are not up-to-date. So, we may need your expertise in helping with the TCP Review Queue numbers. What do you suggest?

**Comment by TracyLinder** [comment]
**Response Sent To Mani:**

Hi Mani, 

I do appreciate being copied on issues with the TCP Tracker however I am not the SPOC for the application. 

I’ve opened a DTS request for this, and copied our team members who are best able to help with data tracker requests. 

All The Best,

Tracy Linder
IT Business Systems Analyst Sr.
Data and Technology Services 
Austin Transportation Department

**Comment by dianamartin** [comment]
I ran into Ryan Ward here at Cameron to ask him about this. He explained he wants to know per submittal review how long it's been "Under Review" and wants to know the which submittals have the longest amount of times. Ex. 9 days is their performance metric. 

So if a submittal is going on 7 days without a review, they would want to know about it.

**Comment by amenity** [comment]
Thanks, @dianamartin! Any idea about level of effort on this? More than days?

**Comment by dianamartin** [comment]
@amenity I haven't received screen shots for this yet. I'm estimating hours
