### ISSUE TITLE
Add "Non-Corridor" record to Corridor Re-Timing Management module

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#216]
Jonathan Lammert
AMD

Talked to John about how we were going to address the Signal Re timing Dashboard request.

**Comment by dianamartin** [comment]
- [ ] Need to add new `System Name` - "Non- Corridor" to the multi choice option. 
- [ ] Need to import the signals that need to be associated as ad hoc re-timing, not part of a corridor

**Comment by dianamartin** [comment]
[Individual Re-timed signals FY2019.xlsx](https://github.com/cityofaustin/atd-knack-data-tracker/files/3632659/Individual.Re-timed.signals.FY2019.xlsx)

**Comment by dianamartin** [comment]
I found the object table I needed to update `signal_corridor_signals`. I added a new signal to the Non-Corridor so that I could export the table headings and populate it using Jonathan's spreadsheet. 

Successfully imported 158 signal records and they're associated to the `NON-CORRIDOR` record.

@johnclary What ever you need to do to create that Signal Re-timing report widget, i think it's ready.

**Comment by dianamartin** [comment]
This need `Review QA` from John. Probably need to move to Sprint 8.

**Comment by johnclary** [comment]
@dianamartin thanks. The "non-corridor" is showing up correctly on the dashboard, and I can confirm that we do not double-count the signals if they are part of other corridors on the list.

Can you ask Jonathan to review, and point out that the "Engineer Note" can be changed?

**Comment by dianamartin** [comment]
@johnclary I forgot to add my note about them wanting to change the "Engineer Note". 

>Modify Engineer Note to have (Public Facing) on Data Tracker, so user knows that notes will appear on the public dashboard.

I'll reach out to Jonathan to review.

**Comment by dianamartin** [comment]
@johnclary are we able to add a new widget to show the "non-corridor" work that happened in 2019? One that looks like this
![image](https://user-images.githubusercontent.com/21112975/65967375-1c3b0c00-e427-11e9-94c6-abdd3c838fa9.png)

Also why in 2020 does the signal count go back up to 403? Instead of maintaining the 341 number in 2019?

**Comment by dianamartin** [comment]
@johnclary I need to follow up with Jonathan to see if he's okay with the dashboard the way it is or if we need to make significant changes to the FY 2020 page.

Are you okay with us adding that new widget, would we task Tyler to help on this?

**Comment by johnclary** [comment]
Let's move this to the issue dedicated for this: https://github.com/cityofaustin/atd-data-and-performance/issues/319

**Comment by johnclary** [comment]
This can be closed as far as I know. @dianamartin ?

**Comment by dianamartin** [comment]
let me catch Jonathan today, i saw him around to confirm if we should work on this now or towards the end of FY 20.

**Comment by dianamartin** [comment]
@johnclary I just spoke to Jonathan and he said it doesn't need to be changed right now. Around January when the start putting data in, he said he can make a new request for a dashboard update. So I'm closing this now.
