### ISSUE TITLE
Bug: Stephanie Moorer unable to log in

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-knack-data-tracker#225]
From Stephanie: Tracy, the Data Tracker is the only thing I could not access. It does not accept my credentials (email/password).

**Comment by dianamartin** [comment]
@TracyLinder This is because an account for Stephanie hasn't been created yet. Knack still requires it before they can use COACD. Let me do that now.

**Comment by dianamartin** [comment]
emailed user
>An account on the Data Tracker application had to be added for you. You should be able to use the COACD button now to access the application.
