### ISSUE TITLE
Signs Migration to Knack project kick-off

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-data-tracker#23]
**Objective** 
Kick off project!

**Participants**
Diana, Amenity, Lauren, Anthony, Christina, Cathy, Kati

**Docs**
 - [Project Brief](https://cityofaustin.sharepoint.com/:p:/s/ATD/DTS/EfSGXjffqB9EujjELQMHPNIBiWzm_4kdS7R4qFwBQPrdFA)
 - [Statement of Work Details](https://cityofaustin.sharepoint.com/:w:/s/ATD/DTS/EaiFJ5maGWdBkiZSUOrb-SABWlYrveBFKp6LpiyQ234vBA)
 - [Meeting notes](https://docs.google.com/document/d/1PnxVAay6uTzuRfqGjv9U5LjFKrgDhPadFQIV9sqPLXA/edit#)

**Comment by amenity** [comment]
@dianamartin - will you add links to the project brief and SOW in the issue description? Should there be a wiki page about this project that has those? /cc @johnclary

**Comment by dianamartin** [comment]
@amenity The url links are updated on the issue description.

**Comment by johnclary** [comment]
@amenity @dianamartin i think it make sense to have a wiki page (in this repo) that has a project summary and links to artifacts. BUT i can also see it being a headache to remember which repo/wiki to go to for project info, and for that reason i wonder if a parent issue/epic would be a better place to keep project info. thoughts?

**Comment by dianamartin** [comment]
@amenity @johnclary I think turning this into an epic would probably make sense. We will have a lot of issues to create for this project.

**Comment by amenity** [comment]
@dianamartin @johnclary — we can try keeping the whole project in an epic, but I think it will be more issues than make sense for a single epic. That's why we have the `Project:` labels — so there can be epics like "Such and such reporting" or "User testing" with sub-issues of their own. 

It seems a little weird that one would have to dig up a specific issue to find general project information. Why would it be a headache to remember what wiki to go to? Isn't it pretty simple to think "All the Data Tracker Knack projects have project info in the `atd-knack-data-tracker` wiki? 🤔

**Comment by amenity** [comment]
We could say that the wiki page (or top-level section page) title should always match the `Project:` label so there's a consistent way to find general project info.

**Comment by dianamartin** [comment]
I added the project docs to a wiki I just made for this project: [Project: Signs Migration](https://github.com/cityofaustin/atd-knack-data-tracker/wiki/Project:-Signs-Migration)
