### ISSUE TITLE
Open Data Meeting - 11/20/2019

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-knack-data-tracker#242]

**Comment by johnclary** [comment]
@SurbhiBakshi would you add any notes and close this?

**Comment by SurbhiBakshi** [comment]
@johnclary looks like this is a duplicate, Mike and I added our notes to [#932] (https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/932)
