### ISSUE TITLE
Created public page for Traffic Count requests (for researchers) to access attachments

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#244]
Natalia R. 
UT

Talked to requester per John's instruction. Evaluated what her data needs are and she will need access to the Traffic Counts request page on the Data Tracker. We will need to create a public page for these requests so that (researchers, requesters) can easily download the attachments they need for research.

**Comment by dianamartin** [comment]
@johnclary Created public page, can you please review page before I give account access to Natalia? [page](https://data.mobility.austin.gov/data-tracker/#home/traffic-count-traffic-data-requests/traffic-counts-public/)

**Comment by johnclary** [comment]
@dianamartin looks great!

**Comment by dianamartin** [comment]
@johnclary Should I keep it "public" _without log on_ or create a new user role for "public access" so we can figure out who we've given access to (ie. researchers, partner agencies..etc...) 

This will determine if Natalia even needs credentials if we have a page like this.

**Comment by johnclary** [comment]
it depends on if Natalia intends to access this data from the API. we will not want to put a login in front of this if she is going to pull this via API.

**Comment by amenity** [comment]
Page is created; will probably have a follow-up request to implement API access to the data.
