### ISSUE TITLE
Locations for VZA 

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-knack-data-tracker#250]

**Comment by SurbhiBakshi** [comment]
Locations - Corridors, Intersection, Schools.

Forms to add new locations, tables to show existing locations. 

Process on the back end to integrate Lewis's list based on the High Injury Network with Jen's list from Data Tracker, which will also incorporate Council Districts, zip codes, and APD Sectors. 

@amenity adding a new issue to show work done last week for locations, and work I need to do this week. (so the 3 Estimate). Let me know if you think this needs to be done another way.

**Comment by amenity** [comment]
Issue moved to [cityofaustin/atd-data-tech #1009](https://github.com/cityofaustin/atd-data-tech/issues/1009) via [**ZenHub**](https://www.zenhub.com/)

**Comment by amenity** [comment]
@SurbhiBakshi Thanks! Adding your notes to this existing issue: https://github.com/cityofaustin/atd-data-tech/issues/994
