### ISSUE TITLE
Add "Cancelled" status for TCP reviews

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-data-tracker#254]
> What application are you using?

Data Tracker

> Describe the problem.

We were hoping to add a submission status for "Cancelled" TCP plans.  This would help to identify plans that are no longer needed by the customer.
Diana Martin and I also talked about removing the second Doug from our Reviewers list.

> How soon do you need this?

Flexible  — An extended timeline is OK

---
Requested by Laura R., ROW
Request ID: DTS20-100375

**Comment by amenity** [comment]
For context of discussion, see [this comment](https://github.com/cityofaustin/atd-knack-data-tracker/issues/252#issuecomment-570354722) on a request by TE for a related Data Tracker enhancement.

**Comment by dianamartin** [comment]
on `tcp_tracking_submissions` object table
Add choice on field: `SUBMISSION_STATUS` - CANCELLED

Create new `NUMBER` field: `STATUS_CANCELLED`

Set conditional rule:
SUBMISSION_STATUS is CANCELLED - 1
SUBMISSION_STATUS is no CANCELLED - 0

on `tcp_tracking` object table

Add `SUM` field - `SUM_CANCELLED`
Add choice on field: `TCP_STATUS` - CANCELLED
Add conditional rule for field `TCP_STATUS` 
cancelled

**Comment by dianamartin** [comment]
### TESTING
`TCP19-026335`
Making the 3rd submission go from "Review in Progress" to "Cancelled"

**Comment by dianamartin** [comment]
### Test record in PROD
`TCP20-027950`

**Comment by dianamartin** [comment]
Added `Cancelled` status to TCP Tracking
