### ISSUE TITLE
Need ability to review "Flex Notes"

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#59]
>As a Signs Assigner & Signs Technician, I need the ability to review Flex Notes that are entered on a 311 Service Request as it gives me information about what the citizen is inquiring/requesting. 

 (minimum abilities that were in Maximo) 

**Have a button to see “Flex Notes” in a details page** (modal pop-up?)

**Comment by amenity** [comment]
@dianamartin add Flex notes as table in work orders

**Comment by dianamartin** [comment]
Added **Flex Notes** as a button on **Service Request | Signs> Details** page.
![image](https://user-images.githubusercontent.com/21112975/58733621-9d6f8d00-83ba-11e9-9621-fc35b69818df.png)

![image](https://user-images.githubusercontent.com/21112975/58733655-b8da9800-83ba-11e9-91ff-bfc555a957ab.png)

**Comment by dianamartin** [comment]
Once **Service Requests** are converted to a **Work Order**, the **Work Order Details** page has a **Flex Notes** table - working on this

**Comment by dianamartin** [comment]
Yes, we fixed this.
