### ISSUE TITLE
Need ability to add Specifications 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#65]
**User Story**
>As a Signs Technician, I need to be able to enter Specifications of the work that was completed so that Signs Internal staff members can use data for reporting purposes. 

**FUNCTION**

- [ ] Import Signs specifications 
- [ ] Add Specification form, Specification tables already exists

**Comment by amenity** [comment]
We have to make a decision on where to add specifications - either jobs or work orders.

**Comment by dianamartin** [comment]
Need to remove a Page Rule (Currently 8)

Remove from hidden
Remove "When" - Technician Role
- [ ] Add Time
- [ ] Add specification
- [ ] Add Inventory Transaction

![image](https://user-images.githubusercontent.com/21112975/58737863-d4e53600-83c8-11e9-8dc2-cf1f257e7d37.png)
