### ISSUE TITLE
Need ability to associate spatial assets to street segment IDs (to align with markings)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#71]
**User Story**
>As a Signs Internal Staff team member, I’m requested (making required?) that all work orders are associated to a Street Segment ID 

>As a Transportation Engineer, I need the ability to enter a Street Segment ID as it is being asked of me by the Signs Internal Staff team members. 

>As a Geospatial technician working on signs work orders, I need the ability see Street Segment IDs referenced in the work order so that I can create assets in the asset datasets.  

**FUNCTION**
- [ ] Have field for “Street Segment ID” visible on the GIS QA filter page?

**Comment by johnclary** [comment]
This is currently accomplished via the `locations` object. All assets are tied to a `location`, all locations are tied to at least one street segment.
