### ISSUE TITLE
Include ATD Service Area field in 311/ESB Integration

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#84]
- Request "Area" field from Omar/311 - need as basic MVP (was getting this field populated and coming over in Maximo)

Description from Issue #58 
 >As a Signs Assigner, I need the ability to quickly review the Service Request and read the short description of the CSR to determine which Signs technician to assign work to (based on the geographic area referenced in the SR label).

(Service Area, Address Block, Address, District Number)
**(Ex. C, 600, Sabine St, 2)**

See if we can concatenate description from data 311 SR System sends over to be Title of SR

**Comment by dianamartin** [comment]
@johnclary 

Created fields:
- `ENGINEER_AREA_csr` (_https://builder.knack.com/atd/amd#data/object_171/fields/**field_3194**_)
- `DISTRICT_csr` (_https://builder.knack.com/atd/amd#data/object_171/fields/**field_3193**_)

in `csr_signs_issues` object table in PROD

You said that ESB would needs these in order to be able to field map the "District" and "Engineer Area" into Knack.

**Comment by johnclary** [comment]
This service area data is flowing in test and will be included in the production release. The council district will not be included on day one, but can be added shortly after. We may be able to accomplish this with a Python script in the meantime.
