### ISSUE TITLE
Rename fields in object table "csr_signs_issues"

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#87]
Identify all field that come from CSR system 
Rename fields to have "_CSR" as a prefix or sufffix

**Comment by dianamartin** [comment]
I chose to tag all field with a "_csr" as a suffix. 

- **EMI_ID**: `2018-000000000000016233`
- **CSR_ID**: `439048293`
- **SR_NUMBER**: `18-00184544`
- **PRC_CODE**: `SIGNPARK`, `SIGNSCHO`, `SIGNTRAF`, `SIGNTRA1`, `SIGNSTRE'
- **PRC_DESC**: `Sign - Street Name`, `Sign - School Zone Sign Maintenance`
- **CSR_Y_VALUE**: `10096591`
- **CSR_X_VALUE**: `3133220`
- **CREATED_DATE_CSR**: `12/18/2018 00:00`
- **STATUS_CODE**: `OPEN`
- **STATUS_DESC**: `Open`
- **METHOD_RECEIVED_CODE**: `PHONE`
- **METHOD_RECEIVED_DESC**: `Phone`
- **PRIORITY_CODE**: `STANDARD, URGENT`
- **PRIORITY_CODE_DESC**: `Standard, Urgent`
- **OWNER_GROUP_CODE**: `SIGNSAND`
- **OWNER_GROUP_DESC**:
- **CSR_DETAILS**: `TEST, DO NOT PROCESS`
- **CSR_ADDRESS**: ex. `1520 RUTHERFORD LN, AUSTIN,TX, 78754`
- **PARTICIPANT_CODE**: `CITIZE1, TRENGCOA`
- **PARTICIPANT_DESC**: Ex. `Citizen, COA Employee`
- **PARTICIPANT_NAME**: ex. `Doe, Jane`
- **PARTICIPANT_PHONE**: ex. `512-900-1000`
- **PARTICIPANT_EMAIL**: ex. `ewatter@email.com`

**Comment by johnclary** [comment]
@dianamartin is this done?

**Comment by dianamartin** [comment]
@johnclary This is done
