### ISSUE TITLE
5/23 Requirements gathering: Markings CSR work flow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-data-tracker#97]
### Attendees
SMB: Lauren, Kati, Christina, Cathy Kambalouris
DTS: Diana, Amenity

### Notes
- [Meeting notes](https://cityofaustin-my.sharepoint.com/:o:/r/personal/diana_martin_austintexas_gov/_layouts/15/WopiFrame.aspx?sourcedoc=%7B434b1a50-7b27-4d30-864e-21740e23f0da%7D&action=default&cid=0ada1192-8e14-4dc3-a902-514877f99d5a)
- [Annotated 311 CSR Workflow PDF](https://github.com/cityofaustin/atd-knack-data-tracker/files/3214843/CSR_311_Markings_Workflow_Future_20171019_Updated_Comments.pdf)

**Comment by amenity** [comment]
@dianamartin - this can be closed after you add the link to the PDF.

**Comment by dianamartin** [comment]
@amenity : I can't find my annotated comments on the markings csr work flow .pdf. I'm not sure if I saved it.. 🤦‍♀

**Comment by amenity** [comment]
😢oh no!!

**Comment by dianamartin** [comment]
I ended up adding the comments from memory and saving as a new version of the work flow with the annotated comments. I added it to the first issue details, let me know if you think I missed anything. I'm going to share it with Christina and Kati to see if they recall any other details.

**Comment by amenity** [comment]
Looks great to me. 👍
